### ISSUE TITLE
done function non blocking

### ISSUE THREAD

**Issue by saidone75** [tlight/spin#1]
Hello Tim,
I would make the function `done` blocking, otherwise a following print can appear before the "✓".
Cheers,
Marco

**Comment by tlight** [comment]
Hi, thanks for the suggestion!
I believe that since `(done)` pushes onto an unbuffered chan, `>!!` is already blocking per [docs](https://clojure.github.io/core.async/#clojure.core.async/%3E!!).

I'll take a closer look and will probably add this to the test suite.

**Comment by saidone75** [comment]
Hmmm, I think you're right. Could be that `alt!` consume the message and unlock the thread before `(ok)` is actually executed.

**Comment by saidone75** [comment]
Working nicely now, thanks!

As side note, I don't think it's necessary to wrap chan into an atom but is only a cosmetic change.

**Comment by saidone75** [comment]
Sorry I was too optimistic:
```
(defn test-spin [spinner]
  (spin/spin :type spinner :ms 100)
  (print (str spinner) " ")
          (Thread/sleep 1000)
          (spin/done)
          (println " OK"))

(deftest spin-test
  (testing "spin"
    (run!
     test-spin
     (keys spin/spinners))))
```
here's the output, most of the time `✓` is printed after `OK`
```
lein test tlight.spin-test
:spin1   OK
✓:box4   OK
✓:spin6   OK✓
:spin3   OK✓
:spin5   OK✓
:spin4  ✓ OK
:spin9   OK
✓:box7   OK
✓:spin2  ✓ OK
:box3   OK
✓:box6   OK
✓:box5   OK✓
:box1   OK✓
:box2   OK
✓:spin8   OK
✓:spin7   OK
✓
Ran 1 tests containing 0 assertions.
0 failures, 0 errors.
```

**Comment by tlight** [comment]
Ha yes, I was also puzzling over similar test output! 
I think I landed on a relatively neat solution where the unbuffered chan signals `:done` then blocks until `:ok` per your original suggestion. 

Resolved my test cases! Let me know how you go (bumped to 0.0.3)

```clj
✓ done 1
----8<----
✓ done 396
✓ done 397
✓ done 398
✓ done 399
✓ done :box1
✓ done :box2
✓ done :box3
✓ done :box4
✓ done :box5
✓ done :box6
✓ done :box7
✓ done :spin1
✓ done :spin2
✓ done :spin3
✓ done :spin4
✓ done :spin5
✓ done :spin6
✓ done :spin7
✓ done :spin8
✓ done :spin9  
```

**Comment by saidone75** [comment]
Great, now tests are looking good!

It stopped compiling with GraalVM though, I think because of `locking` (pretty sure that removing it won't hurt).

Thanks again!

**Comment by tlight** [comment]
I wound back the locking per your suggestion and everything is still behaving...
Thanks again for you contributions!

**Comment by saidone75** [comment]
Works like a charm now and compile with Graal :)

Thank you very much!

Marco

Tim writes:

> I wound back the locking per your suggestion and everything is still
> behaving...  Thanks again for you contributions!
